### ISSUE TITLE
Can improve the docs/guide/server-hot-update.md

### ISSUE THREAD

**Issue by dsonet** [fibjs/fibjs.org#54]
```javascript
coroutine.start(function() {
    while (true) {
        coroutine.sleep(1000);
        svr.handler = new_web();
    }
})
```
doesn't need to create a new instance every seconds, can check if the file changed first(like to see if the last-modified changed)

**Comment by xicilion** [comment]
u r right, this is just an example of how to hot upgrade, it is not a complete functional program..
